### ISSUE TITLE
There is a question in your code

### ISSUE THREAD

**Issue by rapcircus** [parthpower/placement-heuristics#1]
How do I run run_me.bat?

**Comment by parthpower** [comment]
I have a typo in the [README.md](README.md), It's actually [run_it.bat](run_it.bat).

If you're on Windows just double-click it. 

On Linux or OSX, open the terminal and execute the command which you can find in the [run_it.bat](run_it.bat) files.

**Comment by rapcircus** [comment]
Thank you for answer. I am looking for a way to run a .bat file in my current Mac environment.

  Looking at the python code, it seems to be the code that calculates the optimal position of the sensor in two dimensions (x, y).

  Currently, I use the estimate beacon to find the optimal beacon location by applying a genetic algorithm to a receiver at a specific location. So now, I want to write code for three-dimensional space. Do you have any publicly available information about this?

**Comment by parthpower** [comment]
For Mac, just open the appropriate HTML file, copy the command line that starts with `python` in your terminal. Simple!
To run Genetic algorithm,
Open [show_svg_Genetic.html](show_svg_Genetic.html) and run this command in the terminal
https://github.com/parthpower/placement-heuristics/blob/6aa4bb8bd7b6fc5f409bfcd02ec2498a8a08865e/run_it_Genetic.bat#L2

Use the basic concept of Genetic algorithm to implement in 3D space. I don't have any such information at the hand.

**Comment by rapcircus** [comment]
Thank you for your response.
